listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
user=turnuser:8-vycN_EfBfhMdqm0sQRcZZ8K-E
realm=voicecom.turbulent.net
external-ip=100.42.169.34
no-multicast-peers
no-cli
no-loopback-peers
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
