listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
user=turnuser:turnpass
realm=voicecom
log-file=/var/log/coturn/turnserver.log
no-multicast-peers
no-cli
# Required for Docker
external-ip=192.168.3.205
